### ISSUE TITLE
Lost grid not working

### ISSUE THREAD

**Issue by soniCaH** [alxshelepenok/gatsby-starter-lumen#35]
When following the installation instructions I end up with a page without grid system.
Seems like the lost grid is not loaded/executed:

<img width="882" alt="screen shot 2017-03-24 at 11 54 30" src="https://cloud.githubusercontent.com/assets/789034/24291302/b1ba9cd4-1088-11e7-87e8-798368469930.png">

<img width="874" alt="screen shot 2017-03-24 at 11 55 06" src="https://cloud.githubusercontent.com/assets/789034/24291312/be9cd750-1088-11e7-9571-614e04b5d52f.png">

**Comment by wpioneer** [comment]
it's weird.
Could you give more information about the system and version of Gatsby?

**Comment by soniCaH** [comment]
Sure, am using Mac OS X Sierra (10.12.3)
gatsby 0.12.39 (installed via `$ sudo npm install -g gatsby`)

**Comment by discordianfish** [comment]
This happened to me too. Same thing: lost-column was still in CSS and not transpiled. I only ever saw it in the build, never in `gatsby develop`. After not being able to reproduce it locally I just re-ran my build and it worked. Maybe some dependency which wasn't pinned and cause this?

**Comment by discordianfish** [comment]
Actually no, I can reproduce this in my CI: Everything built locally works, everything on the CI does not. This is my circle.yml:
```
machine:
  nodejs: 4.2.6

dependencies:
  pre:
    - npm install
    - cat npm-debug.log || true

test:
  override:
    - "true"

deployment:
  production:
    branch: master
    commands:
      - git config --global user.email "xx"
      - git config --global user.name "Johannes 'fish' Ziemke"
      - GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_xx" npm run deploy
```
