### ISSUE TITLE
table CSS need

### ISSUE THREAD

**Issue by acbetter** [alxshelepenok/gatsby-starter-lumen#79]
Hiya~ I'm using your theme (gatsby-v2 branch) and there seems nothing for table css. Here's my opinion for css table style.
```scss
## _generic.scss

table {
    display: block;
    font-size: $typographic-small-font-size;
    line-height: $typographic-table-line-height;
    width: 100%;
    & tr {
        &:nth-child(even) {
            background-color: $color-table-tbody;
        }
    }
    & th {
        color: white;
        background-color: $color-table-thead;
        min-width: 80px;
    }
    & td {
        text-align: left;
        padding-left: 1rem;
    }
    & img {
        width: 15px;
        height: 15px;
    }
}
```
